<?php

/**
 * @file
 * ir_extention_ui.module
 */

/**
 * Implements hook_menu().
 */
function ir_extention_ui_menu() {
  $items['admin/config/user-interface/ir_extention'] = array(
    'title' => 'IR Extention',
    'description' => 'IR Extention instance settings list.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ir_extention_settings_form'),
    'access arguments' => array('administer ir_extention settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ir_extention_ui.admin.inc',
  );
  $items['admin/config/user-interface/ir_extention/%'] = array(
    'title' => 'IR Extention Instance Settings',
    'description' => 'List instance settings.',
    'page callback' => 'ir_extention_instance_settings_form',
    'page arguments' => array(4),
    'access arguments' => array('administer ir_extention settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ir_extention_ui.admin.inc',
  );
  $items['admin/config/user-interface/ir_extention/import'] = array(
    'title' => 'Import Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ir_extention_variable_settings_import_form'),
    'access arguments' => array('administer ir_extention settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ir_extention_ui.admin.inc',
  );
  $items['admin/config/user-interface/ir_extention/%/export'] = array(
    'title' => 'Export Settings',
    'page callback' => 'ir_extention_export_instance_settings',
    'page arguments' => array(4),
    'access arguments' => array('administer ir_extention settings'),
    'type' => MENU_CALLBACK,
    'file' => 'ir_extentionl_ui.admin.inc',
  );
  $items['admin/config/user-interface/ir_extention/%/delete/%'] = array(
    'title' => 'Delete Settings',
    'page callback' => 'ir_extention_delete_instance_settings',
    'page arguments' => array(4, 6),
    'access arguments' => array('administer ir_extention settings'),
    'type' => MENU_CALLBACK,
    'file' => 'ir_extention_ui.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function ir_extention_ui_permission() {
  return array(
    'administer ir_extention settings' => array(
      'title' => t('Administer IR Extention settings'),
    ),
  );
}

/**
 * Implements hook_variable_settings_form_alter().
 */
function ir_extention_ui_variable_settings_form_alter(&$form, $form_state, $form_id) {
  if (isset($form_state['build_info']['args'][0]) && $form_state['build_info']['args'][0] == 'ir_extention') {
    $instance = $form_state['build_info']['args'][1];

    // Include additional submit handler to update settings cache.
    $form['#submit'][] = 'ir_extention_variable_settings_submit';

    // This needs a graceful solution... =/
    $settings = ir_extention_ui_build_instance_settings($instance, $form['#variable_edit_form']);
    foreach ($form as $key => $component) {
      if (strpos($key, '[instance_id]') !== FALSE) {
        $form[$key] = $settings[$key];
      }
    }
  }
}

/**
 * Format variable settings form to only display our
 * instance variables.
 */
function ir_extention_ui_build_instance_settings($instance, $settings) {
  module_load_include('form.inc', 'variable');

  foreach ($settings as $key => $setting) {
    $variable = variable_get_child($setting, $instance);
    $form[$setting][$variable['name']] = variable_form_element($variable);

    if ($setting == 'ir_extention_navigation_text_[instance_id]') {
      $form[$setting][$variable['name']][0]['#title'] = t('Previous');
      $form[$setting][$variable['name']][1]['#title'] = t('Next');
    }
  }

  return $form;
}

/**
 * Helper function, return list of setting variables.
 */
function _ir_extention_return_setting_vars() {
  $query = 'SELECT name FROM {variable} WHERE name LIKE :name';
  $results = db_query($query, array(':name' => db_like('ir_extention_') . '%'))->fetchAll();

  return $results;
}
